name: toda

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    timeout-minutes: 5

    permissions:
      id-token: write
      contents: read

    steps:

      - name: Use Node.JS 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '1'

      - name: Build toda
        run: |
          npm ci

      - name: Test
        run: npm test
